# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
docs/openapi.yaml:
  no-server-example.com:
    - '#/servers/0/url'
swagger/components/responses.yaml:
  no-unused-components:
    - '#/Ok'
    - '#/Created'
    - '#/Updated'
